### ISSUE TITLE
Feature: User can select a class

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can select a class.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can select a class  from a drop down list of classes available. 
The selection will fill-in information about the selected class on the page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
https://www.figma.com/file/Mk6LKeXGFQWhK5aYQujq3j/D-and-D-app?node-id=0%3A1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create base html
- [x] Create base CSS
- [x] Create mobile and desktop views
- [x] Test mobile and desktop resizing
- [x] Create a drop-down list where the user can select a class name
- [x] Create an array to house the class description text
- [x] Upon class selection, the icon on the left changes to appropriate class icon
- [x] Upon class selection, the api is called for class information on the selected class.
- [x] DOM creation event made, taking the api information and attaching it to the correct element
- [x] Test each class selection
- [x] Test mobile and desktop resizing with DOM created elements
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
