### ISSUE TITLE
Design Update: When clicking the roll dice button a 3d die rolls on screen

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#12]
## ⚙️ Feature

> ##### Which feature is affected by this update?

## 📐 Plan

> ##### Summary of the technical approach to be taken.

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add the word "Directory" to the top site bar
- [x] When you click on the "spells by class" toggle on a class that has no spells, have a message that says "this class can't use spells" or something to that effect.
- [x] Add rolling dice animation to the dice rolls
- [x] Make the top navButton stay yellow when you're on that section page
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
