### ISSUE TITLE
Polish: Separate the rending functions from the xhr requests

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#13]
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] List out the functions renders to separate from the xhr requests. 
- [x] Create new functions for each render
- [x] call the render functions in the xhr requests
- [x] test the render functions for errors
- [x] add a print out of each individual roll for rolls of more than one die. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Spell-check and grammar-check all hard-coded text, like buttons, labels, and headings.
- [x] When data fetching or search results lists are empty, show a message informing the user that there were no results found.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile (375px x 812px) and desktop (1280px x 720px) screens.
  - [x] Confirm that resizing the browser window from mobile, to desktop and back does not look "broken" at any point.
  - [x] Create GIFs of the app being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
