### ISSUE TITLE
Polish: Clean up spell list class refreshing and dice rolling

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#16]
## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] When rolling the dice, it would be awesome to have the numbers rolled displayed on the center of the background die
- [ ] It would be good to prevent the user from spamming the Roll button for the dice rolls, as it can cause some visual weirdness with the rolling die
- [ ] For the Spells view, there appears to be inconsistency in the functionality, specifically if you select a level of spells, and change the classes, the content starts to have the wrong information,
- **Clean Up**
  - [ ] Remove all buttons and placeholders that don't do anything.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile (375px x 812px) and desktop (1280px x 720px) screens.
  - [ ] Confirm that resizing the browser window from mobile, to desktop and back does not look "broken" at any point.
  - [ ] Create GIFs of the app being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
