### ISSUE TITLE
Feature: User can see all spells listed by level

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see all spells listed by level

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can select a specific level or all, and see all the spells in that listing. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
https://www.figma.com/file/Mk6LKeXGFQWhK5aYQujq3j/D-and-D-app?node-id=0%3A1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] HTML /CSS for the spell page
- [x] addEventListener for spells button click to change the page to the spells page
- [x] add spell buttons - all, 0-9
- [x] when clicking on the spell buttons, the appropriate spell list generates
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
