### ISSUE TITLE
Feature: User can view spell details

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view spell details

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can see spell details by clicking on the spell name. A modal pops up that shows the details of the spell that was selected. 
Clicking out of the modal box will return the user to spell list. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://www.figma.com/file/Mk6LKeXGFQWhK5aYQujq3j/D-and-D-app?node-id=0%3A1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create overlay and modal window in HTML & CSS
- [x] add an event listener to trigger the modal appearing
- [x] add an event listener to trigger the modal disappearing
- [x] pull the individual spell information into the modal when the user triggers it
- [x] test different spells to ensure the proper information is displaying
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
