### ISSUE TITLE
Feature: User can filter spell list by class

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter spell list by class. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can filter spells by the selected class. The spell list will function the same as it did previously, but showing only spells available to the selected class. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://www.figma.com/file/Mk6LKeXGFQWhK5aYQujq3j/D-and-D-app?node-id=0%3A1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a filter spells by class
- [x] add an event listener to filter the spells when the button is pressed
- [x] when the button is pressed a second time the filter is removed. 
- [x] test all previous features with the newly added filter button
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
