### ISSUE TITLE
Feature: User can roll specific dice

### ISSUE THREAD

**Issue by stefancarrera** [stefancarrera/dnd-directory#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can roll specific dice

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can roll specific dice with modifiers and get the result sent back. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://www.figma.com/file/Mk6LKeXGFQWhK5aYQujq3j/D-and-D-app?node-id=0%3A1

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] HTML and CSS for the dice page.
- [x] Create buttons for each die
- [x] when the button is pressed, change the die image
- [x] Test page changing
- [x] Test dice roller API
- [x] make an event listener for the roll button that connects the dice and the modifiers to produce a roll
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
